# Generated by Django 5.0.6 on 2024-08-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='owner',
            managers=[
            ],
        ),
    ]
