# Generated by Django 5.0.6 on 2024-07-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите новую запись', max_length=100, verbose_name='Запись')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('photo', models.ImageField(help_text='Загрузите новое фото', upload_to='product/photo', verbose_name='Фото')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Введите дату загрузки', verbose_name='Дата создания')),
                ('views_counter', models.PositiveIntegerField(default=0, help_text='Укажите количество просмотров', verbose_name='Счетчик просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['name', 'description'],
            },
        ),
    ]
