# Generated by Django 5.0.6 on 2024-07-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='введите вашу почту', max_length=100, verbose_name='ваша почта')),
                ('full_name', models.CharField(help_text='введите ваше ФИО', max_length=100, verbose_name='ВАШЕ ФИО')),
                ('comments', models.TextField(help_text='оставьте свой комментарий', max_length=200, verbose_name='ваш комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(auto_now_add=True, verbose_name='Дата последней попытки')),
                ('status', models.CharField(choices=[('ok', 'Успешно'), ('failed', 'Ошибка')], default='ok', max_length=20, verbose_name='Статус')),
                ('server_response', models.CharField(blank=True, max_length=350, null=True, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Тело')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Пиьсма',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='время старта')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('period', models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default='daily', max_length=20, verbose_name='Период')),
                ('status', models.CharField(choices=[('created', 'Запущена'), ('started', 'Создана'), ('done', 'Завершена')], default='created', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
                'permissions': [('deactivate_mailing', 'Can deactivate mailing'), ('view_all_mailings', 'Can view all mailings')],
            },
        ),
    ]
